### ISSUE TITLE
Put the puzzle pieces into a nice grid.

### ISSUE THREAD

**Issue by roymcavoy** [Pixabay/jQuery-snapPuzzle#1]
Can we have an option where the puzzle pieces can be lay out in a nice grid instead of randomly scattered in the pile dive?

Thanks.

**Comment by bingquan3846** [comment]
Hi, I used this plugin in our project recently , there is a problem  for the width of source images. please start the puzzle after this source image is loaded. Anyway, if you do not want to randomly distribute the pieces, you should modify the plugin. I just read the code , it is fixed. Good Luck.

**Comment by brunogarcia** [comment]
Hi @roymcavoy , I made a fork with exactly that behaviour.

Use: start_puzzle({'grid': 2, 'randomly': false});

https://github.com/brunogarcia/jQuery-snapPuzzle

Cheers!

**Comment by roymcavoy** [comment]
Hi @brunogarcia,

Thanks very much. You rocks man! :D :+1:
