### ISSUE TITLE
Source Image

### ISSUE THREAD

**Issue by RodriAndreotti** [Pixabay/jQuery-snapPuzzle#3]
Hello,

Its possible to get the source image hidden?

**Comment by lapinos03** [comment]
If you look at the source of the demo (https://goodies.pixabay.com/jquery/snap-puzzle/demo.html), you will find that line that specifies the opacity :

.snappuzzle-slot { position: absolute; background: #fff; opacity: .8; }

Change opacity to 1 and the source image will be hidden.

**Comment by RodriAndreotti** [comment]
Hello, thanks. I had already decided, just by changing this line. =]

**Comment by SimonSteinberger** [comment]
We might improve documentation on this.
